# Generated by Django 2.2.3 on 2020-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='画像ファイル名')),
                ('staffname', models.CharField(max_length=30, verbose_name='スタッフの名前')),
                ('bestmuscle', models.CharField(max_length=20, verbose_name='チャームポイントなる筋肉名')),
                ('workouthistory', models.CharField(max_length=10, verbose_name='トレーニング歴')),
                ('comment', models.CharField(max_length=300, verbose_name='一言')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
