# Generated by Django 3.1.1 on 2020-10-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201004_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='workouthistory',
            field=models.IntegerField(verbose_name='トレーニング歴'),
        ),
    ]
