# Generated by Django 3.1.1 on 2020-10-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='画像ファイル名')),
                ('goodsname', models.CharField(max_length=30, verbose_name='商品の名前')),
                ('price', models.IntegerField(verbose_name='金額')),
                ('comment', models.CharField(max_length=500, verbose_name='商品紹介')),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
    ]
