# Generated by Django 2.2.3 on 2020-09-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='動画ファイル名')),
                ('title', models.CharField(max_length=20, verbose_name='動画タイトル')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
