# Generated by Django 2.2.3 on 2020-10-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='filename',
            field=models.CharField(max_length=200, verbose_name='動画ファイル名(.mp4形式で記述)'),
        ),
    ]
