# Generated by Django 3.1.1 on 2020-10-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201003_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='動画説明'),
        ),
    ]
